### ISSUE TITLE
"." and "@" not accepted as valid characters for resource name

### ISSUE THREAD

**Issue by PeterJamesHarrison** [oracle/terraform-provider-baremetal#17]
Code:
resource "baremetal_identity_user" "john.smith@nowhere.com" {
  name = "john.smith@nowhere.com"
  description = "John Smith - User Account"
}

Error Message:
  * baremetal_identity_user.john.smith@nowhere.com: john.smith@nowhere.com: resource name can only contain letters, numbers, dashes, and underscores.

Note, console accepts:  "No spaces. Only letters, numerals, hyphens, periods, underscores, +, and @."

**Comment by craigcarl-oracle** [comment]
Confirmed, thanks Peter. We will get a fix shipped this week.

Reference: https://docs.us-phoenix-1.oraclecloud.com/api/#/en/identity/20160918/User/CreateUser

**Comment by craigcarl-oracle** [comment]
@PeterJamesHarrison  - Turns out that error message isn't about the name you're passing to the BMC, it's the TF resource name - ```resource "baremetal_identity_user" "john.smith@nowhere.com" ```. 

You are going to need to do something like - 
resource "baremetal_identity_user" "john-smith_nowhere-com" {
name = "john.smith@nowhere.com"
description = "John Smith - User Account"
}
