### ISSUE TITLE
Create subnet issue from teraform...

### ISSUE THREAD

**Issue by chatchai-komrangded** [oracle/terraform-provider-baremetal#38]
I've tested "complete_vcn" example for demo propose, but facing following issues below:

Error applying plan:

9 error(s) occurred:

* baremetal_core_subnet.BastionSubnetAD2: Code: InternalError; OPC Request ID: /F46D517E7A2941B08E9419AA6DA808AE/E7C8A6A7C2F4469CAC2B31729C5A50A9; Message: Internal error occurred
* baremetal_core_subnet.PrivateSubnetAD1: Code: InternalError; OPC Request ID: /1A857A362C03463A8832C6D4A7581954/923B66FEE0A74D45A310F67DC140D6E0; Message: Internal error occurred
* baremetal_core_subnet.BastionSubnetAD3: Code: NotAuthorizedOrNotFound; OPC Request ID: /0FE07B59D5214C27A7114B7F3DB9B273/C0FB59F6A57E476AA6A47D82F1C84A55; Message: Either VCN with ID ocid1.vcn.oc1.phx.aaaaaaaavzzt3djeu4az2mxm3nn7t6wl4smncy7mpu7ldlghzsvkdd6wmx6a does not exist or you are not authorized to access it.
* baremetal_core_subnet.WebSubnetAD1: Code: InternalError; OPC Request ID: /7181518A998F48A5AB9EF406F39F1D72/9123B3293D8E474297AC697DA0A68896; Message: Internal error occurred
* baremetal_core_subnet.WebSubnetAD3: Code: InternalError; OPC Request ID: /A0FBA0B18C1E46D98BD2F0541E203EB1/9EBEAB3604CF483F89AF229D2F3D5C8F; Message: Internal error occurred
* baremetal_core_subnet.PrivateSubnetAD2: Code: InternalError; OPC Request ID: /EB543571B69B4D7B953657D7F7E093E2/593CD696B9A94F1690C04065108C5A16; Message: Internal error occurred
* baremetal_core_subnet.BastionSubnetAD1: Code: InternalError; OPC Request ID: /97FD414EC9464371BA3021B9B572608E/80CCAC3901AA4D4780DF0B68F6C5CE47; Message: Internal error occurred
* baremetal_core_subnet.WebSubnetAD2: Code: InternalError; OPC Request ID: /C5ACC1D8FE684F66AA77C0B1D90FFE17/2EE38BFDBA0744F49FB0778120F96ACE; Message: Internal error occurred
* baremetal_core_subnet.PrivateSubnetAD3: Code: InternalError; OPC Request ID: /60FB8F1B27714BC198AC293BBA32EBAA/898D91FC834F438893621FAC63A4C19F; Message: Internal error occurred

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

I'm using teraform version 0.8.8

Any suggest to sort this issue ?

**Comment by srinatar** [comment]
Hi
  This error is most likely because the terraform template that you are using to build upon is not updated to use your account specific AD code information. The sample file uses a example AD unique code such as ‘Uocm-“ or something like that. If in case, your sample terraform has a .tf like this 

variable "ADs" {
  default = ["Uocm:PHX-AD-1", "Uocm:PHX-AD-2", "Uocm:PHX-AD-3"]
}

then, you need to find out your tenancy specific AD unique code and then use it in this variable 

for example, I setup CLI access as shown here - https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/cli.htm <https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/cli.htm> and then I ran the below command 

(cli)srsrnata-mac2:oracle-bmc srsrnata$ bmcs iam availability-domain list -c ocidv1:tenancy:oc1:phx:1459361676919:aaaaaaaavmtu2tcvtzpus5ooit4w7dwc6q | grep name
      "name": "JnEv:PHX-AD-1"
      "name": "JnEv:PHX-AD-2"
      "name": "JnEv:PHX-AD-3”

now, If I update my terraform above variable definition to reflect my AD specific unique code, then you should be able to create the subnets. 

variable "ADs" {
  default = [“JnEnv:PHX-AD-1", "JnEnv:PHX-AD-2", "JnEnv:PHX-AD-3"]
}

Hope this helps
Sriram

**Comment by chatchai-komrangded** [comment]
Hi Sriram,

Thanks !! you save my time on that, yes now i've done all "complete_vcn" stuff !

**Comment by craigcarl-oracle** [comment]
Another way to do this is to use the [baremetal_identity_availability_domain](https://github.com/oracle/terraform-provider-baremetal/blob/master/docs/datasources/identity/availability_domain.md) datasource.

Get a list of your ADs - 
```data "baremetal_identity_availability_domains" "ads" {
  compartment_id = "${var.compartment_ocid}"
}```

Use that list on a resource -

```resource "baremetal_core_instance" "Bastion" {
    availability_domain = "${lookup(data.baremetal_identity_availability_domains.ads.availability_domains[0],"name")}"
    compartment_id = "${var.compartment_ocid}"
    display_name = "Bastion"
    image = "${lookup(data.baremetal_core_images.OLImageOCID.images[0],"id")}"
    shape = "${var.BastionShape}"
    subnet_id = "${baremetal_core_subnet.BastionSubnetAD1.id}"
    metadata {
        ssh_authorized_keys = "${var.ssh_key_4_metadata}"
	user_data = "${base64encode(file(var.BastionBootStrap))}" 
    }
}```

TF counts from 0 so [0] is AD-1, [1] is AD-2, [2] is AD-3.
